### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by mars** [dreamhouseapp/dreamhouse-pio#1]
After following the complete three-app deployment instructions in the [README](https://github.com/dreamhouseapp/dreamhouse-pio/blob/master/README.md), the app ends up in a **crashed** state.

It seems to be a JSON parse error during `EngineWorkflow.train`.

Log output:

```
2016-08-01T18:03:09.331122+00:00 heroku[web.1]: Starting process with command `source bin/env.sh && target/universal/stage/bin/dreamhouse-pio -main ServerApp`
2016-08-01T18:03:12.056348+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2016-08-01T18:03:12.854398+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx350m -Xss512k -Dfile.encoding=UTF-8
2016-08-01T18:03:27.645643+00:00 app[web.1]: [WARN] [NativeCodeLoader] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-08-01T18:03:29.060665+00:00 app[web.1]: [INFO] [Remoting] Starting remoting
2016-08-01T18:03:30.621997+00:00 app[web.1]: [INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@a06f533a-e3bf-42ef-81b7-6a1a03f12e8d.prvt.dyno.rt.heroku.com:38484]
2016-08-01T18:03:36.839138+00:00 app[web.1]: [INFO] [Engine$] EngineWorkflow.train
2016-08-01T18:03:36.839637+00:00 app[web.1]: [INFO] [Engine$] DataSource: DataSource@51ec2856
2016-08-01T18:03:36.846590+00:00 app[web.1]: [INFO] [Engine$] Preparator: Preparator@1f53481b
2016-08-01T18:03:36.847103+00:00 app[web.1]: [INFO] [Engine$] AlgorithmList: List(Algorithm@6f70a21b)
2016-08-01T18:03:36.889045+00:00 app[web.1]: [INFO] [Engine$] Data sanity check is on.
2016-08-01T18:03:38.572127+00:00 app[web.1]: Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Cannot': was expecting ('true', 'false' or 'null')
2016-08-01T18:03:38.572202+00:00 app[web.1]:  at [Source: org.apache.commons.httpclient.AutoCloseInputStream@2ef0dd86; line: 1, column: 8]
2016-08-01T18:03:38.572413+00:00 app[web.1]:  at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
2016-08-01T18:03:38.572457+00:00 app[web.1]:  at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
2016-08-01T18:03:38.572618+00:00 app[web.1]:  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
2016-08-01T18:03:38.572619+00:00 app[web.1]:  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
2016-08-01T18:03:38.572676+00:00 app[web.1]:  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
2016-08-01T18:03:38.572726+00:00 app[web.1]:  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
2016-08-01T18:03:38.572796+00:00 app[web.1]:  at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
2016-08-01T18:03:38.572862+00:00 app[web.1]:  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
2016-08-01T18:03:38.572919+00:00 app[web.1]:  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2207)
2016-08-01T18:03:38.572998+00:00 app[web.1]:  at org.json4s.jackson.JsonMethods$class.parse(JsonMethods.scala:21)
2016-08-01T18:03:38.573058+00:00 app[web.1]:  at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:44)
2016-08-01T18:03:38.573111+00:00 app[web.1]:  at DataSource.readTraining(DataSource.scala:27)
2016-08-01T18:03:38.573196+00:00 app[web.1]:  at DataSource.readTraining(DataSource.scala:15)
2016-08-01T18:03:38.573253+00:00 app[web.1]:  at io.prediction.controller.PDataSource.readTrainingBase(PDataSource.scala:37)
2016-08-01T18:03:38.573322+00:00 app[web.1]:  at io.prediction.controller.Engine$.train(Engine.scala:641)
2016-08-01T18:03:38.573393+00:00 app[web.1]:  at io.prediction.controller.Engine.train(Engine.scala:174)
2016-08-01T18:03:38.573449+00:00 app[web.1]:  at io.prediction.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:65)
2016-08-01T18:03:38.573574+00:00 app[web.1]:  at TrainApp$.train(TrainApp.scala:75)
2016-08-01T18:03:38.573652+00:00 app[web.1]:  at ServerApp$delayedInit$body.apply(ServerApp.scala:11)
2016-08-01T18:03:38.573724+00:00 app[web.1]:  at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
2016-08-01T18:03:38.574638+00:00 app[web.1]:  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
2016-08-01T18:03:38.574734+00:00 app[web.1]:  at scala.App$$anonfun$main$1.apply(App.scala:71)
2016-08-01T18:03:38.574791+00:00 app[web.1]:  at scala.App$$anonfun$main$1.apply(App.scala:71)
2016-08-01T18:03:38.575226+00:00 app[web.1]:  at scala.collection.immutable.List.foreach(List.scala:318)
2016-08-01T18:03:38.575274+00:00 app[web.1]:  at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
2016-08-01T18:03:38.576060+00:00 app[web.1]:  at scala.App$class.main(App.scala:71)
2016-08-01T18:03:38.576103+00:00 app[web.1]:  at ServerApp$.main(ServerApp.scala:9)
2016-08-01T18:03:38.576159+00:00 app[web.1]:  at ServerApp.main(ServerApp.scala)
2016-08-01T18:04:09.636575+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-08-01T18:04:09.636665+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-08-01T18:04:09.859962+00:00 heroku[web.1]: Process exited with status 137
2016-08-01T18:04:09.874264+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by jamesward** [comment]
Make sure there isn't a trailing slash on the `DREAMHOUSE_WEB_APP_URL` value.

**Comment by Prasath18** [comment]
When I click the recommendation in web app, its showing nothing.
and showing given error 
2017-07-26T04:35:47.419542+00:00 heroku[router]: at=info method=GET path="/recommendations" host=webapppio.herokuapp.com request_id=84c2099a-4f22-4f4d-ba6a-8d27e509ebdb fwd="103.219.207.45" dyno=web.1 connect=1ms service=414ms status=200 bytes=202 protocol=https
2017-07-26T04:35:47.413429+00:00 app[web.1]: Failed to get recommendations for user = 0057F000000ZpOfQAK --- verify that the user has favorited a property and then relearn in PIO

**Comment by jamesward** [comment]
@Prasath18 It seems like the model you are using wasn't trained or doesn't have recommendations for the given user.  Can you email me and we can debug this? `j.ward <at> salesforce.com`
